export const AUTH = 'AUTH'
export const ADD_TO_BASKET = 'ADD_TO_BASKET'
export const FILL_BASKET = 'FILL_BASKET'
export const SUBTRACT_QTY = 'SUBTRACT_QTY'
export const ADD_QTY = 'ADD_QTY'
export const DELETE_ITEM_FROM_BASKET = 'DELETE_ITEM_FROM_BASKET'
